### ISSUE TITLE
Kanban and Custom View

### ISSUE THREAD

**Issue by AGELIOS** [axelor/axelor-development-kit#27]
Can we use Kanban and Custom View presents in the developper's guide with the adk 3.0.22 ?
I tried to use but the tags kanban and custom are not recognized in eclipse after have installed the version 3.0.22 of adk.

regards,

**Comment by marioestradarosa** [comment]
I guess you have to check out the dev branch, otherwise it won't be available (at least kanban, cards view etc).
 
|   |
| 
|  |   | Mario Estradaabout.me/marioestradarosa |

   |
|   |

**Comment by AGELIOS** [comment]
I have got downloaded the adk.zip and compiled it.
I have compiled my modules and when I run it, the about page show that the axelor version is well 3.0.22.
But when i want to use Kanban, custom or Card view in Eclipse, tags are not recognized.
I don't find anything about kanban view in the source files of adk and particularly in the object-views.xsd file. Is it normal ?

**Comment by marioestradarosa** [comment]
You have to check out the dev branch, that's the only one for the moment that has the kanban partials and logic.The Team hasn't merged it with the main branch yet, dev is version 4.0 , perhaps the Team can accelerate this commit ?.. anyone ? , because official documentation is actually mentioning it. 


git clone -b dev https://github.com/axelor/axelor-development-kit.git

notice the -b switch option , it is specified the dev branch. Actually if you click on branches on the browser you can go to webapp/partials/views and you'll see the kanban.html . 

 

|   |
| 
|  |   | Mario Estradaabout.me/marioestradarosa |

   |
|   |

 


     On Wednesday, October 28, 2015 8:35 AM, AGELIOS <notifications@github.com> wrote:
   

 Reopened #27.—

**Comment by mea-axelor** [comment]
These features are in upcoming v4.0 version only which dev branch.

The documentation is work in progress and updated to reflect features in current dev branch. We are taking steps to host version specific documentation to avoid confusion.
